@RBStorageApiUrl = https://localhost:7067

### Get all users
GET {{RBStorageApiUrl}}/users
Accept: application/json
###


# POST {{RBStorageApiUrl}}/users/add
# Content-Type: application/json

# {
#   "Email": "lukwis95@gmail.com",
#   "Password": "RBStorage123"
# }

###
