@RBStorageApiUrl = https://localhost:7067

### Get all users
GET {{RBStorageApiUrl}}/users
Accept: application/json
###

# ### Add a new user
# POST {{RBStorageApiUrl}}/users/add
# Content-Type: application/json

# {
#   "Email": "aniaszadurska@wp.pl",
#   "Password": "password123*%$",
# }
# ###
