openapi: 3.0.0
info:
  title: CodeService API
  version: 1.0.0
paths:
  /generate:
    get:
      summary: Generate a code
      parameters:
        - name: CodeType
          in: query
          required: false
          schema:
            type: integer
            default: 0
            description: "Specifies the type of code to generate. Valid values are between 0 and 1. If not provided, the default value is 0."
        - name: Quantity
          in: query
          required: false
          schema:
            type: integer
            default: 1
            description: "Specifies the number of codes to generate. If not provided, the default value is 1."
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  Codes:
                    type: array
                    items:
                      type: string
        '400':
          description: Bad Request - Invalid CodeType
        '500':
          description: Internal Server Error
