openapi: 3.0.0
info:
  title: CodeService API
  version: 1.0.0
paths:
  /generate:
    get:
      summary: Generate a code
      parameters:
        - name: CodeType
          in: query
          required: false
          schema:
            type: integer
            description: "Specifies the type of code to generate. 1 for a verification code. If not provided, a default random string is generated."
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties:
                      VerificationCode:
                        type: string
                  - type: object
                    properties:
                      Code:
                        type: string
        '400':
          description: Bad Request - Invalid CodeType
